export const PUBLIC_FEED_START: 'PUBLIC_FEED_START' = 'PUBLIC_FEED_START';
export const PUBLIC_FEED_SUCCESS: 'PUBLIC_FEED_SUCCESS' = 'PUBLIC_FEED_SUCCESS';
export const PUBLIC_FEED_ERROR: 'PUBLIC_FEED_ERROR' = 'PUBLIC_FEED_ERROR';
export const PUBLIC_FEED_CLOSED: 'PUBLIC_FEED_CLOSED' = 'PUBLIC_FEED_CLOSED';
export const PUBLIC_FEED_GET_MESSAGE: 'PUBLIC_FEED_GET_MESSAGE' = 'PUBLIC_FEED_GET_MESSAGE';
export const PUBLIC_FEED_SEND_MESSAGE: 'PUBLIC_FEED_SEND_MESSAGE' = 'PUBLIC_FEED_SEND_MESSAGE';

export const PRIVATE_FEED_START: 'PRIVATE_FEED_START' = 'PRIVATE_FEED_START';
export const PRIVATE_FEED_SUCCESS: 'PRIVATE_FEED_SUCCESS' = 'PRIVATE_FEED_SUCCESS';
export const PRIVATE_FEED_ERROR: 'PRIVATE_FEED_ERROR' = 'PRIVATE_FEED_ERROR';
export const PRIVATE_FEED_CLOSED: 'PRIVATE_FEED_CLOSED' = 'PRIVATE_FEED_CLOSED';
export const PRIVATE_FEED_GET_MESSAGE: 'PRIVATE_FEED_GET_MESSAGE' = 'PRIVATE_FEED_GET_MESSAGE';
export const PRIVATE_FEED_SEND_MESSAGE: 'PRIVATE_FEED_SEND_MESSAGE' = 'PRIVATE_FEED_SEND_MESSAGE';