export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_ERROR: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';
export const SHOW_ORDER_MODAL: 'SHOW_ORDER_MODAL' = 'SHOW_ORDER_MODAL';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';
export const UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE' = 'UPDATE_TOTAL_PRICE';

export const SET_CURRENT_TAB: 'SET_CURRENT_TAB' = 'SET_CURRENT_TAB';

export const REORDER_CONSTRUCTOR_ITEMS: 'REORDER_CONSTRUCTOR_ITEMS' = 'REORDER_CONSTRUCTOR_ITEMS';
export const ADD_CONSTRUCTOR_ITEM: 'ADD_CONSTRUCTOR_ITEM' = 'ADD_CONSTRUCTOR_ITEM';
export const DELETE_CONSTRUCTOR_ITEM: 'DELETE_CONSTRUCTOR_ITEM' = 'DELETE_CONSTRUCTOR_ITEM';
export const ADD_CONSTRUCTOR_BUN: 'ADD_CONSTRUCTOR_BUN' = 'ADD_CONSTRUCTOR_BUN';
export const DELETE_CONSTRUCTOR_BUN: 'DELETE_CONSTRUCTOR_BUN' = 'DELETE_CONSTRUCTOR_BUN';
export const RESET_CONSTRUCTOR_ITEMS: 'RESET_CONSTRUCTOR_ITEMS' = 'RESET_CONSTRUCTOR_ITEMS';

export const INCREASE_ITEM_COUNTER: 'INCREASE_ITEM_COUNTER' = 'INCREASE_ITEM_COUNTER';
export const DECREASE_ITEM_COUNTER: 'DECREASE_ITEM_COUNTER' = 'DECREASE_ITEM_COUNTER';
export const RESET_BUN_COUNTER: 'RESET_BUN_COUNTER' = 'RESET_BUN_COUNTER';
export const INCREASE_BUN_COUNTER: 'INCREASE_BUN_COUNTER' = 'INCREASE_BUN_COUNTER';
export const RESET_ITEMS_COUNTERS: 'RESET_ITEMS_COUNTERS' = 'RESET_ITEMS_COUNTERS';